sudo: false
language: node_js
node_js:
  - "12"
install:
  - npm install
  - npm i -D markdown-it
  - npm i -D minimist
before_script:
  # get release info
  export RELEASE_NAME=$TRAVIS_TAG
  export RELEASE_NOTE=$(node build/deploy/change-log.js --path=examples/docs/docs/changelog.md --version=$RELEASE_NAME)
script:
  - npm run unit
  - npm run dist
  # build resource code
  - source build/deploy/script.sh
after_success:
  - echo $(node build/deploy/check-deploy.js)
deploy:
  provider: npm
  # ⋮
  edge: true
  skip_cleanup: true
  api_token: $NPM_API_TOKEN
#  api_key:
#    secure: IYbllklBK3N4BhsqAHPON21nz7k8nyRP5d6z+lic27UlONiPZ0xvaN1JxnzbEuKMkIhEXQd6m8v1Ry9hCMf4hSmcZ2QWtSvm/dwXP+mvlbv7S+eXl1jbsZgTx4zo60U+D6SMphMkH4hCjJqpEk5YxfX82cXpJwWRoWQpzQknE1dGlrfcgmyXGoR4rsAUp0VGo2mubWtY/TtOoNRNP2KjOoU5y2D0pPdjp783Hlr0T6oRKM06K0+Pdfw5MhoUqryuGGQdzMefpSUgh2sRW4UaBacoWel8ygYKH1pewRo4rx+hFbP8Ynhy8JjBFq19EHn9GHBucnSaeplkHJP2r95xSmE5DHprSe/TtfhQjD+TQQqqjVnB4+wh4y30bxPCGPkZk5Qy5cfHLhANpHYbVjfba1oy8DM+qcrYB0r787GvF0qO6q2Igj0W3XL5+KAl4WTwn3fcmhafQLhgiF2LXI55JR9iDUj9B2m9vet32IeHA4XvmRRmBB2wL+oCyAc46erxLFK+gsAkZ0YzixqJJZ0HUJ1R58mmnYOtvsbJL7wyoxrgYIJp+JHL190Ofb8j4WYwnzA7s92hn4hEOim6FhAYYfdKceBSLjfA0f2bK/L4PjuWdowFFmXDO7KrxVh9yEOeOGTXbvMEdkJ0zqfoMnd7Kn93Ig1FQFcej715rlZsVaY=
  on:
    tags: true
    condition: $(node build/deploy/check-deploy.js) = true
after_deploy:
  - sh ./build/deploy/after-deploy.sh
